sid=auto
profile=high-quality

# until i get AV1 gpu
ytdl-format=bestvideo[vcodec^=vp9]+bestaudio/best
hwdec-codecs=h264,vc1,hevc,vp8,vp9

# https://github.com/classicjazz/mpv-config/blob/master/mpv.conf
###########
# General #
###########

#nvidia 
vo=gpu-next
hwdec=nvdec


# vulkan-async-compute=yes
# vulkan-async-transfer=yes
# vulkan-queue-count=1
# vd-lavc-dr=yes
#

# https://github.com/classicjazz/mpv-config/blob/master/mpv.conf
term-osd-bar=yes # display a progress bar on the terminal
#

# https://github.com/Zabooby/mpv-config/blob/main/portable_config/mpv.conf
### Audio and Subtitles ###
slang=en,eng,English,en-US,US
alang=ja,jp,jpn,jap,Japanese,en,eng,English
# sub-blur=0.5
# sub-gauss=1.5
# sub-scale=0.8
# sub-margin-y=60
sub-color='#eceff4'
sub-shadow-offset=0
sub-outline-size=1.15
sub-font='JetBrains Mono'
# sub-back-color='#2e3440'
# sub-border-color='#2e3440'
# sub-shadow-color='#2e3440'
# sub-outline-color='#2e3440'
sub-auto=all
volume-max=200
sub-fix-timing=yes
blend-subtitles=yes
sub-ass-override=yes
audio-file-auto=fuzzy
audio-pitch-correction=yes
audio-normalize-downmix=yes
audio-channels=7.1,5.1,stereo
sub-file-paths-append=subtitles
demuxer-mkv-subtitle-preroll=yes
sub-file-paths=sub;subs;subtitles
### OSD ###
no-border
osd-bar=no
osd-bold=yes
osd-font-size=37
osd-font='JetBrains Mono'
#

# https://github.com/HongYue1/mpv-config/blob/main/portable_config/mpv.conf
# ===================================================================
# Screenshot
# ===================================================================
screenshot-format=png
screenshot-high-bit-depth=yes
screenshot-tag-colorspace=yes
screenshot-png-compression=4
screenshot-dir="~/images/mpv_screenshots"
screenshot-template="%{?demuxer-via-network==yes:${media-title}%{?demuxer-via-network==yes:_${filename/no-ext}%{!demuxer-via-network==yes:${filename}-%wH.%wM.%wS.%wT-#%#00n"


[network]
cache=yes
demuxer-max-bytes=512MiB
demuxer-readahead-secs=30
cache-secs=120
